### ISSUE TITLE
make the `addProperty` function take a schema and a simple object of properties to overwrite

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/schema-tools#113]
Doesn't need to be any more complicated than a `_.deepMerge` IMO.

I want the same API as I specify when creating the thing + your extra goodies such as automatic version setting, etc.

Maybe the method could be called `bump` or `extend` or something. I should also be able to specify my own custom version.

**Comment by bahmutov** [comment]
Also, can TypeScript have a type for _non-empty_ array? 
```
addProperty(schema, a) // works
addProperty(schema) // catch this
```
